ALTER TABLE "Project" ADD COLUMN "purpose" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "reference" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "sector" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'EUR';
ALTER TABLE "Project" ADD COLUMN "budgetStated" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Project" ADD COLUMN "lead" TEXT NOT NULL DEFAULT '';

CREATE TABLE "ProjectEvent" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "fileId" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ProjectEvent_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ProjectEvent_projectId_idx" ON "ProjectEvent"("projectId");

ALTER TABLE "ProjectEvent" ADD CONSTRAINT "ProjectEvent_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Client" ADD COLUMN "reference" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Client" ADD COLUMN "sector" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Client" ADD COLUMN "currency" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Product" ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'produit';
ALTER TABLE "Product" ADD COLUMN "statedPrice" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "currency" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "vatNote" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "costStated" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Quote" ADD COLUMN "projectId" TEXT;
ALTER TABLE "Quote" ADD COLUMN "clientName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "currency" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "vatZone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "vatMention" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "statedTotalHt" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "statedVat" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "statedTotalTtc" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Quote" ADD COLUMN "conditions" TEXT NOT NULL DEFAULT '';

CREATE INDEX "Quote_projectId_idx" ON "Quote"("projectId");

ALTER TABLE "Quote" ADD CONSTRAINT "Quote_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "QuoteLine" ADD COLUMN "quantity" TEXT NOT NULL DEFAULT '';
